name: drupal-base
recipe: drupal11
config:
  php: 8.3
  webroot: web
  databse: mysql:8.0.22

services:
  database:
    creds:
      database: drupal
      password: drupal
      user: drupal
  node:
    type: node
    globals:
      gulp: latest
    build:
      - npm install

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node