name: drupal-base
recipe: drupal10
config:
  php: 8.1
  webroot: web
  config:
    php: lando/config/php.ini
  services:
    node:
      type: node
      globals:
        gulp: "latest"
      build:
        - npm install
services:
  appserver:
    composer_version: "2.6.5"
    config:
      php: lando/config/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  composer:
    service: appserver
    cmd: php /usr/local/bin/composer
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node